version: "3.8"

services:
    app:
        build:
            context: .
            target: dev
        container_name: fastify-app
        volumes:
            - ./:/app
            - /app/node_modules
            - /app/build
        ports:
            - "8080:8080"
        environment:
            - NODE_ENV=development
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - DB_HOST=${DB_HOST}
        depends_on:
            - postgres
        command: sh -c "npx sequelize-cli db:migrate --migrations-path src/migrations --config src/config/sequelize-config.js && npx sequelize-cli db:seed:all --seeders-path src/seeders --config src/config/sequelize-config.js && npx nodemon --config nodemon.json --legacy-watch"

    postgres:
        image: postgres:14-alpine
        container_name: fastify-postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
