
services:
    app:
        build:
            context: .
            target: dev
        container_name: fastify-app
        volumes:
            - ./:/app
            - /app/node_modules
            - /app/build
        ports:
            - "8080:8080"
        env_file:
            - ./.env
        environment:
            NODE_ENV: development
        depends_on:
            - postgres
        command: sh ./entrypoint.sh

    postgres:
        image: postgres:14-alpine
        container_name: fastify-postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
