"""add pregnancy table

Revision ID: bfe60ab136f0
Revises: 231b2506dedc
Create Date: 2026-06-17 11:53:31.847913+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe60ab136f0'
down_revision: str | None = '231b2506dedc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pregnancy',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('individual_id', sa.Integer(), nullable=False),
    sa.Column('reproductive_event_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_pregnant', sa.Boolean(), nullable=False),
    sa.Column('offspring_count', sa.Integer(), nullable=True),
    sa.Column('expected_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('is_pregnant OR (offspring_count IS NULL AND expected_due_at IS NULL)', name=op.f('ck_pregnancy_not_pregnant_has_no_projection')),
    sa.CheckConstraint('offspring_count IS NULL OR offspring_count >= 0', name=op.f('ck_pregnancy_offspring_count_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_pregnancy_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name=op.f('fk_pregnancy_farm_id_farm'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['individual_id'], ['individual.id'], name=op.f('fk_pregnancy_individual_id_individual'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reproductive_event_id'], ['event.id'], name=op.f('fk_pregnancy_reproductive_event_id_event'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pregnancy')),
    sa.UniqueConstraint('reproductive_event_id', name=op.f('uq_pregnancy_reproductive_event_id'))
    )
    op.create_index('ix_pregnancy_due', 'pregnancy', ['farm_id', 'expected_due_at'], unique=False, postgresql_where=sa.text('is_pregnant AND expected_due_at IS NOT NULL'))
    op.create_index('ix_pregnancy_farm_individual', 'pregnancy', ['farm_id', 'individual_id'], unique=False)
    op.create_index('uq_pregnancy_farm_idempotency_key', 'pregnancy', ['farm_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_pregnancy_farm_idempotency_key', table_name='pregnancy', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_pregnancy_farm_individual', table_name='pregnancy')
    op.drop_index('ix_pregnancy_due', table_name='pregnancy', postgresql_where=sa.text('is_pregnant AND expected_due_at IS NOT NULL'))
    op.drop_table('pregnancy')
    # ### end Alembic commands ###
