"""add_asset_individual_event_schema

Revision ID: 0a3a3ce9a25e
Revises: 9065664c8821
Create Date: 2026-04-23 12:07:43.949217+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a3a3ce9a25e'
down_revision: str | None = '9065664c8821'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('animal', 'crop', 'equipment', 'material', 'location', name='asset_kind'), nullable=False),
    sa.Column('mode', sa.Enum('aggregated', 'individual', name='asset_mode'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name=op.f('fk_asset_farm_id_farm'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset'))
    )
    op.create_index(op.f('ix_asset_asset_farm_id'), 'asset', ['farm_id'], unique=False)
    op.create_index('ix_asset_farm_kind', 'asset', ['farm_id', 'kind'], unique=False)
    op.create_table('event_category',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('production', 'expense', 'income', 'observation', 'reproductive', name='event_type'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name=op.f('fk_event_category_farm_id_farm'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_category')),
    sa.UniqueConstraint('farm_id', 'type', 'name', name='farm_type_name')
    )
    op.create_index(op.f('ix_event_category_event_category_farm_id'), 'event_category', ['farm_id'], unique=False)
    op.create_table('individual',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=128), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.Column('father_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'sold', 'deceased', 'archived', name='individual_status'), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f('fk_individual_asset_id_asset'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name=op.f('fk_individual_farm_id_farm'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['father_id'], ['individual.id'], name=op.f('fk_individual_father_id_individual'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mother_id'], ['individual.id'], name=op.f('fk_individual_mother_id_individual'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_individual'))
    )
    op.create_index('ix_individual_farm_status', 'individual', ['farm_id', 'status'], unique=False)
    op.create_index(op.f('ix_individual_individual_asset_id'), 'individual', ['asset_id'], unique=False)
    op.create_index(op.f('ix_individual_individual_farm_id'), 'individual', ['farm_id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('individual_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('production', 'expense', 'income', 'observation', 'reproductive', name='event_type'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type <> 'reproductive' OR individual_id IS NOT NULL", name=op.f('ck_event_reproductive_requires_individual')),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f('fk_event_asset_id_asset'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['event_category.id'], name=op.f('fk_event_category_id_event_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_event_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name=op.f('fk_event_farm_id_farm'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['individual_id'], ['individual.id'], name=op.f('fk_event_individual_id_individual'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    op.create_index('ix_event_asset_type_occurred_at', 'event', ['asset_id', 'type', 'occurred_at'], unique=False)
    op.create_index('ix_event_category_id', 'event', ['category_id'], unique=False, postgresql_where=sa.text('category_id IS NOT NULL'))
    op.create_index('ix_event_farm_occurred_at', 'event', ['farm_id', 'occurred_at'], unique=False)
    op.create_index('ix_event_individual_occurred_at', 'event', ['individual_id', 'occurred_at'], unique=False, postgresql_where=sa.text('individual_id IS NOT NULL'))
    op.create_index('uq_event_farm_idempotency_key', 'event', ['farm_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_event_farm_idempotency_key', table_name='event', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_event_individual_occurred_at', table_name='event', postgresql_where=sa.text('individual_id IS NOT NULL'))
    op.drop_index('ix_event_farm_occurred_at', table_name='event')
    op.drop_index('ix_event_category_id', table_name='event', postgresql_where=sa.text('category_id IS NOT NULL'))
    op.drop_index('ix_event_asset_type_occurred_at', table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_individual_individual_farm_id'), table_name='individual')
    op.drop_index(op.f('ix_individual_individual_asset_id'), table_name='individual')
    op.drop_index('ix_individual_farm_status', table_name='individual')
    op.drop_table('individual')
    op.drop_index(op.f('ix_event_category_event_category_farm_id'), table_name='event_category')
    op.drop_table('event_category')
    op.drop_index('ix_asset_farm_kind', table_name='asset')
    op.drop_index(op.f('ix_asset_asset_farm_id'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
